AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Fargate service for stockmarket with public ALB

Parameters:
  DBHost: String
  DBUser: String
  DBPassword: String
  DBDatabase: String
  DBPort:
    Type: String
    Default: "3306"
  AWSRegion: String
  CognitoUserPoolId: String
  CognitoClientId: String
  ImageURLStockMarket: String
  VpcId: String
  PublicSubnet1: String
  PublicSubnet2: String

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: stockmarket-cluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsTaskExecutionRole-stockmarket
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/stockmarket
      RetentionInDays: 7

  StockMarketTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: stockmarket-task
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt [TaskExecutionRole, Arn]
      ContainerDefinitions:
        - Name: stockmarket_service
          Image: !Ref ImageURLStockMarket
          PortMappings:
            - ContainerPort: 5000
          Environment:
            - Name: DB_HOST
              Value: !Ref DBHost
            - Name: DB_USER
              Value: !Ref DBUser
            - Name: DB_PASSWORD
              Value: !Ref DBPassword
            - Name: DB_NAME
              Value: !Ref DBDatabase
            - Name: DB_PORT
              Value: !Ref DBPort
            - Name: AWS_REGION
              Value: !Ref AWSRegion
            - Name: COGNITO_USER_POOL_ID
              Value: !Ref CognitoUserPoolId
            - Name: COGNITO_APP_CLIENT_ID
              Value: !Ref CognitoClientId
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/stockmarket
              awslogs-region: !Ref AWSRegion
              awslogs-stream-prefix: ecs

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ECSServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: stockmarket-alb
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: stockmarket-tg
      Port: 5000
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTP

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: Listener
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ECSServiceSecurityGroup
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
      LoadBalancers:
        - ContainerName: stockmarket_service
          ContainerPort: 5000
          TargetGroupArn: !Ref TargetGroup
      TaskDefinition: !Ref StockMarketTaskDefinition

Outputs:
  ServiceURL:
    Description: Public Load Balancer URL
    Value: !Join ["", ["http://", !GetAtt [LoadBalancer, DNSName]]]
